runtime: python38
# entrypoint: gunicorn -b :$PORT pooling.wsgi

env: standard
instance_class: F2

env_variables:
  DJANGO_ENV: $DJANGO_ENV
  # the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: $SECRET_KEY
  DEBUG: False # always False for deployment

  DB_HOST: /cloudsql/$CLOUD_SQL_INSTANCE
  DB_PORT: "5432" # PostgreSQL port
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: $DB_PASSWORD
  SENDGRID_API_KEY: $SENDGRID_API_KEY

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}

beta_settings:
  cloud_sql_instances: $CLOUD_SQL_INSTANCE
