runtime: python38
# entrypoint: gunicorn -b :$PORT pooling.wsgi

env: standard
instance_class: F2

env_variables:
  DJANGO_ENV: "stage"
  # the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: "e008b206-806b-433d-99b2-e4cffea8f69f"
  DEBUG: "False" # always False for deployment

  DB_HOST: "/cloudsql/tapestry-pooling-284109:europe-west1:postgres"
  DB_PORT: "5432" # PostgreSQL port
  DB_NAME: "pooling"
  DB_USER: "tapestry-staging" # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: "pooling@123"

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /.*
    script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}

beta_settings:
  cloud_sql_instances: tapestry-pooling-284109:europe-west1:postgres
