# Generated by Django 3.0.8 on 2020-07-14 17:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kirkman_matrix', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples', models.SmallIntegerField()),
                ('suspected_samples', models.SmallIntegerField()),
                ('positive_samples', models.SmallIntegerField()),
                ('remark', models.TextField()),
                ('patient_id_map', django.contrib.postgres.fields.jsonb.JSONField()),
                ('results_1', models.TextField()),
                ('results_2', models.TextField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.User')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.File')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.MachineType')),
                ('mastermix_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastermix_matrix', to='rest.Matrix')),
                ('pooling_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pooling_matrix', to='rest.Matrix')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Status')),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.TestKit')),
            ],
        ),
    ]
