# Generated by Django 3.0.8 on 2020-07-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinetype',
            old_name='plate_x',
            new_name='dim_x',
        ),
        migrations.RenameField(
            model_name='machinetype',
            old_name='plate_y',
            new_name='dim_y',
        ),
    ]
