# Generated by Django 3.0.8 on 2020-07-16 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkit',
            name='description',
        ),
        migrations.AddField(
            model_name='testkit',
            name='gene_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=['E gene'], size=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testkit',
            name='kit_maker',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='testkit',
            name='test_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='testkit',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
