# Generated by Django 3.0.8 on 2020-07-31 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_test_prevalence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='suspected_samples',
        ),
        migrations.AddField(
            model_name='test',
            name='inconclusive_samples',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.File'),
        ),
        migrations.AlterField(
            model_name='test',
            name='mastermix_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastermix_matrix', to='rest.Matrix'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pooling_matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pooling_matrix', to='rest.Matrix'),
        ),
        migrations.AlterField(
            model_name='test',
            name='positive_samples',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='results_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='results_2',
            field=models.TextField(blank=True),
        ),
    ]
