# Generated by Django 3.0.8 on 2020-07-31 11:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20200731_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='results_1',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='inconclusive_samples',
            new_name='ninconclusive',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='positive_samples',
            new_name='npositive',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='samples',
            new_name='nsamples',
        ),
        migrations.RemoveField(
            model_name='test',
            name='file',
        ),
        migrations.RemoveField(
            model_name='test',
            name='mastermix_matrix',
        ),
        migrations.RemoveField(
            model_name='test',
            name='patient_id_map',
        ),
        migrations.RemoveField(
            model_name='test',
            name='pooling_matrix',
        ),
        migrations.RemoveField(
            model_name='test',
            name='results_2',
        ),
        migrations.AddField(
            model_name='test',
            name='inconclusive',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='positive',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
