# Generated by Django 3.0.8 on 2020-08-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20200731_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='filename',
            new_name='poolingscheme_filename',
        ),
        migrations.AddField(
            model_name='test',
            name='lab_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='testctresults_filename',
            field=models.TextField(blank=True),
        ),
    ]
