# Generated by Django 3.0.8 on 2020-08-04 10:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20200803_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='lab_id',
        ),
        migrations.AlterField(
            model_name='test',
            name='inconclusive',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='positive',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
