# Generated by Django 3.0.8 on 2020-08-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20200804_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labconfiguration',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Lab'),
        ),
    ]
