# Generated by Django 3.0.8 on 2020-08-24 15:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20200813_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='labconfiguration',
            name='nsamples',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labconfiguration',
            name='poolingmatrix_filename',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labconfiguration',
            name='prevalence',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='negative',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='nnegative',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='poolingmatrix_filename',
            field=models.TextField(blank=True),
        ),
    ]
