# Generated by Django 3.0.8 on 2020-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_auto_20200903_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='poolingmatrix_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='poolingscheme_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='testctresults_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
