# Generated by Django 3.0.8 on 2020-09-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20200927_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Status'),
        ),
    ]
