# Generated by Django 3.0.8 on 2020-10-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_auto_20200927_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labconfiguration',
            name='machine_type',
            field=models.ManyToManyField(default=1, to='rest.MachineType'),
        ),
        migrations.AlterField(
            model_name='labconfiguration',
            name='max_poolsize',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='labconfiguration',
            name='nsamples',
            field=models.SmallIntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='labconfiguration',
            name='prevalence',
            field=models.FloatField(default=7.5),
        ),
        migrations.AlterField(
            model_name='labconfiguration',
            name='test_kit',
            field=models.ManyToManyField(default=1, to='rest.TestKit'),
        ),
    ]
