# Generated by Django 3.0.8 on 2020-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_test_err_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labconfiguration',
            name='poolingmatrix_filename',
            field=models.TextField(blank=True, default='Tapestry_Pooling_24x64.xlsx'),
        ),
    ]
