# Generated by Django 3.0.8 on 2021-03-06 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_auto_20201007_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
