from .lab import LabAdmin
from .user import UserAdmin
from .test import TestAdmin
from .file import FileAdmin
from .lab_configuration import LabConfigurationAdmin
from .machine_type import MachineTypeAdmin
from .matrix import MatrixAdmin
from .test_kit import TestKitAdmin
from .status import StatusAdmin